### ISSUE TITLE
Inject interceptors to undo and redo events

### ISSUE THREAD

**Issue by mebble** [day8/re-frame-undo#5]
I'd like to backup the app data to localstorage when the `:undo` and `:redo` events are dispatched. The `undoable` interceptor doesn't get triggered during these events. Is there a way we can inject code that gets called when the undo/redo events are dispatched?

So far as a [partially successful] workaround, I've use the `:reinstate-fn` to inject code during these events. But this is a hack that doesn't work when our injected code needs access to the context object, which has the coeffects and effects map. Only interceptors have access to the context.

If there's an existing way to do this that would be great. If not, are interceptors the way to include this ability?

**Comment by mebble** [comment]
I made a PR https://github.com/day8/re-frame-undo/pull/6 just to demo it

**Comment by mike-thompson-day8** [comment]
There's probably no need for new features here.  

Two alternative approaches, which use existing features, are:
   1.  write your own harvest and reinstate fns (see https://github.com/day8/re-frame-undo#harvesting-and-re-instating)
   2. Create a re-frame Global Interceptor that checks to see if the event id `:undo` and then does whatever you need done.

**Comment by mebble** [comment]
Thanks I’ll try this out
